"""
Conversion patterns module for ESX to QB-Core and QB-Core to ESX conversions.
"""
from typing import Dict, List, Tuple

def load_conversion_patterns() -> Dict[str, List[Tuple[str, str]]]:
    """
    Load conversion patterns for ESX to QB-Core and QB-Core to ESX.
    Patterns are organized alphabetically within their respective categories.

    Returns:
        Dict[str, List[Tuple[str, str]]]: A dictionary containing lists of tuples for each conversion direction and SQL patterns.
    """
    patterns: Dict[str, List[Tuple[str, str]]] = {
        "ESX_to_QB_Core": [
            ("ESX.GetPlayerData", "QBCore.Functions.GetPlayerData"),
            ("ESX.IsPlayerLoaded", "QBCore.Functions.GetPlayerData().citizenid ~= nil"),
            ("ESX.SetPlayerData", "QBCore:Player:SetPlayerData"),
            ("ESX.TriggerServerCallback", "QBCore.Functions.TriggerCallback"),
            ("ESX.Game.DeleteVehicle", "QBCore.Functions.DeleteVehicle"),
            ("ESX.Game.DeleteObject", "DeleteEntity"),
            ("ESX.Game.GetClosestPed", "QBCore.Functions.GetClosestPed"),
            ("ESX.Game.GetClosestPlayer", "QBCore.Functions.GetClosestPlayer"),
            ("ESX.Game.GetClosestVehicle", "QBCore.Functions.GetClosestVehicle"),
            ("ESX.Game.GetClosestObject", "GetClosestObjectOfType"),
            ("ESX.Game.GetPedMugshot", "RegisterPedheadshot"),
            ("ESX.Game.GetPlayers", "QBCore.Functions.GetPlayers"),
            ("ESX.Game.GetVehicles", "QBCore.Functions.GetVehicles"),
            ("ESX.Game.GetVehicleProperties", "QBCore.Functions.GetVehicleProperties"),
            (
                "ESX.Game.GetVehicleInDirection",
                "QBCore.Functions.GetVehicleInDirection",
            ),
            ("ESX.Game.SpawnVehicle", "QBCore.Functions.SpawnVehicle"),
            ("ESX.Game.SpawnObject", "CreateObject"),
            (
                "ESX.Game.SetVehicleDoorsLocked",
                "QBCore.Functions.SetVehicleDoorsLocked",
            ),
            ("ESX.Game.SetVehicleProperties", "QBCore.Functions.SetVehicleProperties"),
            ("ESX.Game.Teleport", "SetEntityCoords and SetEntityHeading"),
            ("ESX.Game.Utils.DrawText3D", "QBCore.Functions.DrawText3D"),
            ("ESX.ShowInventory", "QBCore:Inventory"),
            ("ESX.ShowNotification", "QBCore:Notify"),
            ("ESX.ShowHelpNotification", "QBCore:Notify"),
            ("ESX.ShowAdvancedNotification", "QBCore:Notify"),
            ("ESX.SavePlayers", "QBCore.Functions.SavePlayers"),
            ("ESX.GetPlayerFromId", "QBCore.Functions.GetPlayer"),
            ("ESX.GetPlayerFromIdentifier", "QBCore.Functions.GetPlayerByCitizenId"),
            ("ESX.GetPlayers", "QBCore.Functions.GetPlayers"),
            ("ESX.RegisterServerCallback", "QBCore.Functions.CreateCallback"),
            ("ESX.RegisterUsableItem", "QBCore.Functions.CreateUseableItem"),
            ("ESX.SavePlayer", "QBCore.Player.Save"),
            ("ESX.UseItem", "QBCore.Functions.UseItem"),
            ("xPlayer.removeWeaponComponent", "xPlayer.Functions.RemoveItem"),
            ("xPlayer.setAccountMoney", "xPlayer.Functions.SetMoney"),
            ("xPlayer.setInventoryItem", "xPlayer.Functions.AddItem"),
            ("xPlayer.setJob", "xPlayer.Functions.SetJob"),
            ("xPlayer.setMoney", "xPlayer.Functions.SetMoney"),
            ("xPlayer.showHelpNotification", "TriggerClientEvent('QBCore:Notify')"),
            ("xPlayer.showNotification", "TriggerClientEvent('QBCore:Notify')"),
            ("xPlayer.getInventoryItem", "exports['qb-inventory']:GetItemByName"),
            ("xPlayer.addInventoryItem", "exports['qb-inventory']:AddItem"),
            ("xPlayer.removeInventoryItem", "exports['qb-inventory']:RemoveItem"),
            ("xPlayer.addMoney", "xPlayer.Functions.AddMoney"),
            ("xPlayer.removeMoney", "xPlayer.Functions.RemoveMoney"),
            ("xPlayer.identifier", "xPlayer.citizenid"),
            ("xPlayer.source", "xPlayer.PlayerData.source"),
            ("esx:addInventoryItem", "QBCore:Server:AddItem"),
            ("esx:getSharedObject", "QBCore:GetObject"),
            ("exports[\"es_extended\"]:getSharedObject()", "exports['qb-core']:GetCoreObject()"),
            ("exports['es_extended']:getSharedObject()", "exports['qb-core']:GetCoreObject()"),
            ("esx:onPlayerDeath", "hospital:server:SetDeathStatus"),
            ("esx:onPlayerSpawn", "QBCore:Client:OnPlayerLoaded"),
            ("esx:playerLoaded", "QBCore:Client:OnPlayerLoaded"),
            ("esx:removeInventoryItem", "QBCore:Server:RemoveItem"),
            ("esx:setAccountMoney", "QBCore:Server:SetMoney"),
            ("esx:showAdvancedNotification", "QBCore:Notify"),
            ("esx:showHelpNotification", "QBCore:Notify"),
            ("esx:showNotification", "QBCore:Notify"),
            ("esx:spawnVehicle", "QBCore:Command:SpawnVehicle"),
            ("esx:useItem", "QBCore:Server:UseItem"),
            ("playerSpawned", "QBCore:Client:OnPlayerLoaded"),
            ("exports.ghmattimysql.execute", "exports.oxmysql:execute"),
            ("exports.ghmattimysql.executeSync", "exports.oxmysql:executeSync"),
            ("exports.ghmattimysql.insert", "exports.oxmysql:insert"),
            ("exports.ghmattimysql.scalar", "exports.oxmysql:scalar"),
            ("exports.ghmattimysql.scalarSync", "exports.oxmysql:scalarSync"),
            ("MySQL.Async.execute", "exports.oxmysql:execute"),
            ("MySQL.Async.fetchAll", "exports.oxmysql:fetchAll"),
            ("MySQL.Async.fetchScalar", "exports.oxmysql:fetchScalar"),
            ("MySQL.Async.insert", "exports.oxmysql:insert"),
            ("MySQL.Sync.fetchAll", "exports.oxmysql:fetchAllSync"),
            ("TriggerEvent('esx:addInventoryItem'", "QBCore:Server:AddItem"),
            ("TriggerEvent('esx:removeInventoryItem'", "QBCore:Server:RemoveItem"),
            ("TriggerEvent('esx:setAccountMoney'", "QBCore:Server:SetMoney"),
        ],
        "QB_Core_to_ESX": [
            ("QBCore.Functions.AddItem", "xPlayer.Functions.AddItem"),
            ("QBCore.Functions.CreateCallback", "ESX.RegisterServerCallback"),
            ("QBCore.Functions.CreateUseableItem", "ESX.RegisterUsableItem"),
            ("QBCore.Functions.DeleteVehicle", "ESX.Game.DeleteVehicle"),
            ("QBCore.Functions.DeleteEntity", "ESX.Game.DeleteObject"),
            ("QBCore.Functions.DrawText3D", "ESX.Game.Utils.DrawText3D"),
            ("QBCore.Functions.GetClosestPed", "ESX.Game.GetClosestPed"),
            ("QBCore.Functions.GetClosestPlayer", "ESX.Game.GetClosestPlayer"),
            ("QBCore.Functions.GetClosestVehicle", "ESX.Game.GetClosestVehicle"),
            ("QBCore.Functions.GetClosestObjectOfType", "ESX.Game.GetClosestObject"),
            ("QBCore.Functions.GetPedheadshot", "ESX.Game.GetPedMugshot"),
            ("QBCore.Functions.GetPlayer", "ESX.GetPlayerFromId"),
            ("QBCore.Functions.GetPlayerByCitizenId", "ESX.GetPlayerFromIdentifier"),
            ("QBCore.Functions.GetPlayerData", "ESX.GetPlayerData"),
            ("QBCore.Functions.GetPlayers", "ESX.GetPlayers"),
            (
                "QBCore.Functions.GetVehicleInDirection",
                "ESX.Game.GetVehicleInDirection",
            ),
            ("QBCore.Functions.GetVehicleProperties", "ESX.Game.GetVehicleProperties"),
            ("QBCore.Functions.Kick", "xPlayer.kick"),
            ("QBCore.Functions.Notify", "ESX.ShowNotification"),
            ("QBCore.Functions.OnJobUpdate", "esx:setJob"),
            ("QBCore.Functions.RemoveItem", "xPlayer.removeInventoryItem"),
            ("QBCore.Functions.RemoveMoney", "xPlayer.removeMoney"),
            ("QBCore.Functions.SavePlayers", "ESX.SavePlayers"),
            ("QBCore.Functions.SavePlayer", "ESX.SavePlayer"),
            ("QBCore.Functions.SetJob", "xPlayer.setJob"),
            ("QBCore.Functions.SetMoney", "xPlayer.setMoney"),
            ("QBCore.Functions.SetPlayerData", "ESX.SetPlayerData"),
            ("QBCore.Functions.SpawnVehicle", "ESX.Game.SpawnVehicle"),
            ("QBCore.Functions.TriggerCallback", "ESX.TriggerServerCallback"),
            ("QBCore.Functions.AddMoney", "xPlayer.addMoney"),
            ("QBCore.Functions.CreateCallback", "ESX.RegisterServerCallback"),
            ("QBCore.Functions.CreateUseableItem", "ESX.RegisterUsableItem"),
            ("QBCore.Functions.DeleteVehicle", "ESX.Game.DeleteVehicle"),
            ("QBCore.Functions.DeleteObject", "ESX.Game.DeleteObject"),
            ("QBCore.Functions.DrawText3D", "ESX.Game.Utils.DrawText3D"),
            ("QBCore.Functions.GetClosestPed", "ESX.Game.GetClosestPed"),
            ("QBCore.Functions.GetClosestPlayer", "ESX.Game.GetClosestPlayer"),
            ("QBCore.Functions.GetClosestVehicle", "ESX.Game.GetClosestVehicle"),
            ("QBCore.Functions.GetClosestObjectOfType", "ESX.Game.GetClosestObject"),
            ("QBCore.Functions.GetPedheadshot", "ESX.Game.GetPedMugshot"),
            ("QBCore.Functions.GetPlayerFromCoords", "ESX.GetPlayerFromCoords"),
            ("QBCore.Functions.GetPlayer", "ESX.GetPlayerFromId"),
            ("QBCore.Functions.GetPlayerByCitizenId", "ESX.GetPlayerFromIdentifier"),
            ("QBCore.Functions.GetPlayerData", "ESX.GetPlayerData"),
            ("QBCore.Functions.GetPlayers", "ESX.GetPlayers"),
            (
                "QBCore.Functions.GetVehicleInDirection",
                "ESX.Game.GetVehicleInDirection",
            ),
            ("QBCore.Functions.GetVehicleProperties", "ESX.Game.GetVehicleProperties"),
            ("QBCore.Functions.Kick", "xPlayer.kick"),
            ("QBCore.Functions.Notify", "ESX.ShowNotification"),
            ("QBCore.Functions.OnJobUpdate", "esx:setJob"),
            ("QBCore.Functions.RemoveItem", "xPlayer.removeInventoryItem"),
            ("QBCore.Functions.RemoveMoney", "xPlayer.removeMoney"),
            ("QBCore.Functions.SavePlayers", "ESX.SavePlayers"),
            ("QBCore.Functions.SavePlayer", "ESX.SavePlayer"),
            ("QBCore.Functions.SetJob", "xPlayer.setJob"),
            ("QBCore.Functions.SetMoney", "xPlayer.setMoney"),
            ("QBCore.Functions.SetPlayerData", "ESX.SetPlayerData"),
            ("QBCore.Functions.SpawnVehicle", "ESX.Game.SpawnVehicle"),
            ("QBCore.Functions.TriggerCallback", "ESX.TriggerServerCallback"),
            ("QBCore:GetObject", "esx:getSharedObject"),
            ("QBCore:Server:AddItem", "esx:addInventoryItem"),
            ("QBCore:Server:RemoveItem", "esx:removeInventoryItem"),
            ("QBCore:Server:SetMoney", "esx:setAccountMoney"),
            ("QBCore:Server:UseItem", "esx:useItem"),
            ("QBCore:Client:OnJobUpdate", "esx:setJob"),
            ("QBCore:Client:OnPlayerLoaded", "esx:onPlayerLoaded"),
        ],
    }
    return patterns
